[package]
name = 'private_coin'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'alin/move-bulletproofs'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
private_coin = "_"